"use client";

import {
  useRef,
  useState,
  useEffect,
  useCallback,
  type ReactNode,
} from "react";
import { ReportSidebar } from "./report-sidebar";
import { sectionIdToCategory, SIDEBAR_CATEGORIES } from "@/lib/section-utils";

interface ReportLayoutProps {
  children: ReactNode;
}

/** Section id and its DOM range; scanned from report content */
interface ScannedSection {
  id: string;
  title: string;
  icon: string;
}

export function ReportLayout({ children }: ReportLayoutProps) {
  const contentRef = useRef<HTMLDivElement>(null);
  const [scannedSections, setScannedSections] = useState<ScannedSection[]>([]);
  const [activeSection, setActiveSection] = useState("overview");

  // Scan DOM for section markers after MDX renders (for grouping only; sidebar shows fixed 6)
  const scanSections = useCallback(() => {
    const container = contentRef.current;
    if (!container) return;

    const markers = container.querySelectorAll<HTMLElement>("[data-section-id]");
    if (markers.length === 0) return;

    const found: ScannedSection[] = [];
    markers.forEach((el) => {
      const id = el.getAttribute("data-section-id") ?? "";
      const title = el.getAttribute("data-section-title") ?? "";
      const icon = el.getAttribute("data-section-icon") ?? "";
      if (id) found.push({ id, title, icon });
    });

    setScannedSections((prev) => {
      if (prev.length === found.length && prev.every((s, i) => s.id === found[i].id)) return prev;
      return found;
    });
  }, []);

  useEffect(() => {
    const container = contentRef.current;
    if (!container) return;
    scanSections();
    const observer = new MutationObserver(() => scanSections());
    observer.observe(container, { childList: true, subtree: true });
    return () => observer.disconnect();
  }, [scanSections]);

  // Show/hide by sidebar category: Overview = only overview block; other tabs = only that category's sections (no overview)
  useEffect(() => {
    const outer = contentRef.current;
    if (!outer) return;

    const inner = outer.querySelector(".report-content") as HTMLElement | null;
    const container = inner ?? outer;

    const markers = container.querySelectorAll<HTMLElement>(":scope > [data-section-id]");
    if (markers.length === 0) return;

    const allChildren = Array.from(container.children) as HTMLElement[];
    const firstMarkerIndex = allChildren.indexOf(markers[0]);
    const overviewElements = allChildren.slice(0, firstMarkerIndex);

    const sectionToElements = new Map<string, HTMLElement[]>();
    markers.forEach((marker, i) => {
      const id = marker.getAttribute("data-section-id") ?? "";
      const start = allChildren.indexOf(marker);
      const nextMarker = markers[i + 1];
      const end = nextMarker ? allChildren.indexOf(nextMarker) : allChildren.length;
      sectionToElements.set(id, allChildren.slice(start, end));
    });

    allChildren.forEach((el) => {
      (el as HTMLElement).style.display = "none";
    });

    if (activeSection === "overview") {
      overviewElements.forEach((el) => {
        (el as HTMLElement).style.display = "";
      });
    } else {
      scannedSections.forEach((s) => {
        if (sectionIdToCategory(s.id) === activeSection) {
          (sectionToElements.get(s.id) ?? []).forEach((el) => {
            (el as HTMLElement).style.display = "";
          });
        }
      });
    }
  }, [activeSection, scannedSections]);

  return (
    <div className="report-page">
      <ReportSidebar
        sections={SIDEBAR_CATEGORIES}
        activeSection={activeSection}
        onSelect={setActiveSection}
      />
      <div className="flex flex-col min-w-0">
        <div ref={contentRef} className="report-content flex-1">
          {children}
        </div>
        {/* Report footer */}
        <div className="mt-8 border-t border-report-border-light px-1 py-4">
          <p className="text-[10px] text-report-text-tertiary">
            This report was generated by AI-powered research and should be verified with local authorities before making investment decisions.
          </p>
        </div>
      </div>
    </div>
  );
}
