import {
  Mountain,
  Landmark,
  Building,
  Flame,
  Droplet,
  Pipette,
  Train,
  Ruler,
  MapPin,
  Clipboard,
  ClipboardList,
  ClipboardCheck,
  TriangleAlert,
  Home,
  CircleDollarSign,
  Calendar,
  Clock,
  Key,
  Scroll,
  HelpCircle,
  Shield,
  Zap,
  TreePine,
  Globe,
  FileText,
  Scale,
  Hammer,
  Truck,
  Wrench,
  Users,
  Phone,
  Mail,
  BookOpen,
  Target,
  TrendingUp,
  BarChart3,
  PieChart,
  Sun,
  LayoutDashboard,
  Search,
  Lightbulb,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  mountain: Mountain,
  landmark: Landmark,
  building: Building,
  flame: Flame,
  droplet: Droplet,
  pipette: Pipette,
  train: Train,
  ruler: Ruler,
  "map-pin": MapPin,
  clipboard: Clipboard,
  "triangle-alert": TriangleAlert,
  home: Home,
  "circle-dollar-sign": CircleDollarSign,
  calendar: Calendar,
  clock: Clock,
  key: Key,
  scroll: Scroll,
  "help-circle": HelpCircle,
  shield: Shield,
  zap: Zap,
  "tree-pine": TreePine,
  globe: Globe,
  "file-text": FileText,
  scale: Scale,
  hammer: Hammer,
  truck: Truck,
  wrench: Wrench,
  users: Users,
  phone: Phone,
  mail: Mail,
  "book-open": BookOpen,
  target: Target,
  "trending-up": TrendingUp,
  "bar-chart": BarChart3,
  "pie-chart": PieChart,
  water: Droplet,
  sewer: Wrench,
  electric: Zap,
  solar: Sun,
  "layout-dashboard": LayoutDashboard,
  "clipboard-list": ClipboardList,
  "clipboard-check": ClipboardCheck,
  search: Search,
  lightbulb: Lightbulb,
};

export function resolveIcon(name: string): LucideIcon | null {
  return ICON_MAP[name] ?? null;
}
